package edu.esa.core.facade;

public enum ErrorType {
    EXPLICIT_INSIGNIFICANT_CHAINS,
    IMPLICIT_INSIGNIFICANT_CHAINS,
    INSIGNIFICANT_CHAINS,
    INCLUSIVE_DUPLICATES,
    COMPLETE_DUPLICATES,
    PARTIAL_DUPLICATES,
    DUPLICATES,
    REDUNDANT_CHAINS,
    REDUNDANT_FOR_INPUT,
    REDUNDANT_FOR_OUTPUT,
    CYCLES,
    CYCLE_CHAINS,
    SIMPLE_CYCLES,
    ISOLATED_VERTICES,
    CONTRADICTING_CHAINS
}
